name: achei
description: "App de achados e perdidos."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_database: ^10.5.7
  mask_text_input_formatter: ^2.0.0
  url_launcher: ^6.0.9
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/AcheiDocs.png"

flutter:

  uses-material-design: true