// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDi8D3ljwpt3dtkj7w8H-P_jrS6-U5XI',
    appId: '1:390960971384:android:f0d21aada815628330778d',
    messagingSenderId: '390960971384',
    projectId: 'acheidocs-c7b8f',
    databaseURL: 'https://acheidocs-c7b8f-default-rtdb.firebaseio.com',
    storageBucket: 'acheidocs-c7b8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1Tkd3OfafrfEONrqszChUwJm_a4P_io',
    appId: '1:390960971384:ios:db9a79d42b3b775430778d',
    messagingSenderId: '390960971384',
    projectId: 'acheidocs-c7b8f',
    databaseURL: 'https://acheidocs-c7b8f-default-rtdb.firebaseio.com',
    storageBucket: 'acheidocs-c7b8f.firebasestorage.app',
    iosBundleId: 'com.example.achei',
  );
}
